const movieData = [
  {
    id: 1,
    poster: 'movie1.jpg',
    title: 'Movie 1',
    country: 'USA',
    year: 2020,
    rottenTomatoRating: 85,
    imdbRating: 7.5,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
  },
  {
    id: 2,
    poster: 'movie2.jpg',
    title: 'Movie 2',
    country: 'UK',
    year: 2019,
    rottenTomatoRating: 78,
    imdbRating: 7.2,
    genre: ['Drama', 'Romance'],
  },
  {id: 3,
    poster: 'movie3.jpg',
    title: 'Movie 3',
    country: 'Canada',
    year: 2021,
    rottenTomatoRating: 90,
    imdbRating: 8.0,
    genre: ['Comedy'],
  },
  {id: 4,
    poster: 'movie4.jpg',
    title: 'Movie 4',
    country: 'France',
    year: 2018,
    rottenTomatoRating: 70,
    imdbRating: 6.7,
    genre: ['Action', 'Thriller'],
  },
  {
    id: 5,
    poster: 'movie5.jpg',
    title: 'Movie 5',
    country: 'Germany',
    year: 2022,
    rottenTomatoRating: 88,
    imdbRating: 7.8,
    genre: ['Horror', 'Mystery'],
  },
  {
    id:6,
    poster: 'movie6.jpg',
    title: 'Movie 6',
    country: 'Spain',
    year: 2017,
    rottenTomatoRating: 82,
    imdbRating: 7.4,
    genre: ['Adventure', 'Fantasy'],
  },
  {
    id: 7,
    poster: 'movie7.jpg',
    title: 'Movie 7',
    country: 'Australia',
    year: 2020,
    rottenTomatoRating: 75,
    imdbRating: 7.0,
    genre: ['Drama'],
  },
  {
    id:8,
    poster: 'movie8.jpg',
    title: 'Movie 8',
    country: 'Japan',
    year: 2019,
    rottenTomatoRating: 84,
    imdbRating: 7.6,
    genre: ['Animation', 'Fantasy'],
  },
  {
    id: 9,
    poster: 'movie9.jpg',
    title: 'Movie 9',
    country: 'South Korea',
    year: 2021,
    rottenTomatoRating: 87,
    imdbRating: 7.9,
    genre: ['Action', 'Crime', 'Drama'],
  },
  {
    id: 10,
    poster: 'movie10.jpg',
    title: 'Movie 10',
    country: 'Brazil',
    year: 2016,
    rottenTomatoRating: 79,
    imdbRating: 7.1,
    genre: ['Comedy', 'Drama'],
  },
  {
    id: 11,
    poster: 'movie11.jpg',
    title: 'Movie 11',
    country: 'India',
    year: 2020,
    rottenTomatoRating: 91,
    imdbRating: 8.1,
    genre: ['Drama', 'Romance'],
  },
  {
    id:12,
    poster: 'movie12.jpg',
    title: 'Movie 12',
    country: 'Mexico',
    year: 2015,
    rottenTomatoRating: 72,
    imdbRating: 6.5,
    genre: ['Action', 'Adventure'],
  },
  {
    id: 13,
    poster: 'movie13.jpg',
    title: 'Movie 13',
    country: 'Germany',
    year: 2021,
    rottenTomatoRating: 76,
    imdbRating: 6.5,
    genre: ['Horror', 'Mystery'],
  },
  {
    id: 14,
    poster: 'movie14.jpg',
    title: 'Movie 14',
    country: 'Spain',
    year: 2020,
    rottenTomatoRating: 87,
    imdbRating: 7.9,
    genre: ['Drama'],
  },
  {
    id: 15,
    poster: 'movie15.jpg',
    title: 'Movie 15',
    country: 'Japan',
    year: 2022,
    rottenTomatoRating: 84,
    imdbRating: 7.3,
    genre: ['Animation', 'Fantasy'],
  },
  {
    id: 16,
    poster: 'movie16.jpg',
    title: 'Movie 16',
    country: 'South Korea',
    year: 2017,
    rottenTomatoRating: 91,
    imdbRating: 8.2,
    genre: ['Drama', 'Mystery'],
  },
  {
    id: 17,
    poster: 'movie17.jpg',
    title: 'Movie 17',
    country: 'Brazil',
    year: 2019,
    rottenTomatoRating: 75,
    imdbRating: 6.8,
    genre: ['Action', 'Adventure', 'Comedy'],
  },
];

export default movieData;
